# Normalization Problem:
: Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as:
𝑍 = 𝑋 − 𝑥̅
𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
.std() calls.
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normaltted: January X, 202X



In [7]:
import numpy as np

# this generate a random 5x5 array and assign it to the variable X
X = np.random.rand(5, 5)

# It calculates the mean and standard deviation of the array
X_mean = X.mean()
X_std = X.std()

#Normalize the array using the formula Z = (X - mean) / std
X_normalized = (X - X_mean) / X_std

# Save the normalized array as a .npy file
np.save('X_normalized.npy', X_normalized)

# Displays the normalized array
print(X_normalized)


[[ 0.16863361  0.88418748 -0.38936744  0.93472757 -0.3125632 ]
 [ 1.88060838  0.22305751  0.33243768  0.11533279  0.56290906]
 [-0.72257026  0.36986592 -1.85694424 -1.62210059 -1.27405855]
 [ 1.57630046  0.88257686  1.30234297 -1.16891517 -0.42385151]
 [-1.40419664 -0.77261848  0.75241602 -0.73907136  0.70086115]]


# DVISISIBLE BY 3 PROBLEM: 
Create the following 10 x 10 ndarray.
𝐴 =
[
1 4 ⋯ 81 100
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
8281 8464 ⋯ 9801 10000]
which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 3. Save the result as div
_by_3.npyary X, 202X


In [9]:
# Initialize two empty lists: one for squared values and another for values divisible by 3
Squared = []
div3=[]
#Loops through from 1-100 and squares each iteration and appends it to the "Squared" list
for y in range(1, 101):
    Squared.append(y**2)
# Convert the "squared" list to a 10x10 NumPy array and store it in the variable "q"
q = np.array(Squared).reshape(10,10)

# Iterate through the "squared" list and append values divisible by 3 to the "div3" list

for i in Squared:
    if i%3 == 0:
        div3.append(i)
#saves the div3 list to "div by 3.npy"
np.save('div by 3.npy', div3)
#To show the 10x10 ndarray
q

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [11]:
np.load('div by 3.npy')
#it loads the list of the values that are divisible by 3 that was saved to 'div_by_3.npy'

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])